# Generated by Django 4.2.9 on 2024-01-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortner',
            new_name='URL',
        ),
    ]
