# Generated by Django 4.2.9 on 2024-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
