# Generated by Django 4.2.9 on 2024-02-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_alter_counter_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
